In [1]:
import numpy as np
import pandas as pd

In [2]:
orders = pd.read_csv('/content/ECommerce_Orders_.csv')

In [3]:
orders.head()

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5
1,ORD002,Priya Reddy,Bangalore,Clothing,T-Shirt,2,1200,Card,4
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4

In [4]:
orders.tail()

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5
11,ORD012,Sneha Rao,Chennai,Clothing,Jacket,1,3500,Card,4
12,ORD013,Kiran Das,Pune,Home,Lamp,2,1800,Cash,3
13,ORD014,Anjali Singh,Mumbai,Electronics,Smartwatch,1,12000,UPI,5
14,ORD015,Vikram Patel,Bangalore,Clothing,T-Shirt,2,1200,Card,4

In [5]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      15 non-null     object
 1   Customer      15 non-null     object
 2   City          15 non-null     object
 3   Category      15 non-null     object
 4   Product       15 non-null     object
 5   Quantity      15 non-null     int64
 6   Unit_Price    15 non-null     int64
 7   Payment_Mode  15 non-null     object
 8   Rating        15 non-null     int64
dtypes: int64(3), object(6)
memory usage: 1.2+ KB

In [6]:
orders.describe()

        Quantity    Unit_Price     Rating
count  15.000000     15.000000  15.000000
mean    1.466667  11960.000000   4.200000
std     0.639940  17308.825164   0.774597
min     1.000000   1200.000000   3.000000
25%     1.000000   2000.000000   4.000000
50%     1.000000   3500.000000   4.000000
75%     2.000000  15000.000000   5.000000
max     3.000000  65000.000000   5.000000

Task 1 — High-Value Order Investigation Dataset: E-Commerce Orders

Concepts: Boolean filtering, &, |, isin(), column selection

1)  Find orders where Category = Electronics, Sales > ₹20,000, Rating >= 4, and Payment_Mode is UPI or Card. (Calculate Sales first as Quantity × Unit_Price.)
2)  Display only Order_ID, Customer, Product, Sales, Rating, Payment_Mode.

In [7]:
orders['sales'] = orders['Quantity'] * orders['Unit_Price']

In [8]:
orders.columns[0]

'Order_ID'

In [9]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      15 non-null     object
 1   Customer      15 non-null     object
 2   City          15 non-null     object
 3   Category      15 non-null     object
 4   Product       15 non-null     object
 5   Quantity      15 non-null     int64
 6   Unit_Price    15 non-null     int64
 7   Payment_Mode  15 non-null     object
 8   Rating        15 non-null     int64
 9   sales         15 non-null     int64
dtypes: int64(4), object(6)
memory usage: 1.3+ KB

In [10]:
orders[(orders['Category']=='Electronics') & (orders['sales'] > 20000) & (orders['Rating'] >= 4) & (orders['Payment_Mode'].isin(['UPI','Card']))][['Customer','Product','sales','Rating','Payment_Mode']]

        Customer Product  sales  Rating Payment_Mode
0   Rahul Sharma  Laptop  65000       5          UPI
2    Arjun Kumar  Mobile  25000       5          UPI
10   Arjun Kumar  Tablet  30000       5          UPI

Task 2 — Customer Name Analysis
Dataset: E-Commerce Orders

Concepts: String methods and derived columns
1) Create an uppercase version of Customer.
2) Create a First_Name column.
3) Find customers whose first name starts with A or R.
4) Find customers whose name contains 'ra', ignoring case.
5) Create a Name_Length column.

In [11]:
orders['Customer_upper'] = orders['Customer'].str.upper()

In [12]:
orders['First_name'] = orders['Customer'].str.split(" ").str[0]

In [13]:
orders['First_name'].head(1)

0    Rahul
Name: First_name, dtype: object

In [14]:
orders[orders['First_name'].str.lower().str.startswith(('a', 'r'))]

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,sales,Customer_upper,First_name
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,RAHUL SHARMA,Rahul
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5,25000,ARJUN KUMAR,Arjun
5,ORD006,Rahul Sharma,Hyderabad,Clothing,Jeans,1,2200,UPI,5,2200,RAHUL SHARMA,Rahul
6,ORD007,Anjali Singh,Mumbai,Electronics,Monitor,1,18000,Card,4,18000,ANJALI SINGH,Anjali
9,ORD010,Rohit Verma,Delhi,Electronics,Keyboard,3,1500,Cash,5,4500,ROHIT VERMA,Rohit
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5,30000,ARJUN KUMAR,Arjun
13,ORD014,Anjali Singh,Mumbai,Electronics,Smartwatch,1,12000,UPI,5,12000,ANJALI SINGH,Anjali

In [15]:
orders[orders['Customer'].str.contains('ra',case = False)]

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,sales,Customer_upper,First_name
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,RAHUL SHARMA,Rahul
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3,5000,SNEHA RAO,Sneha
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4,6000,KIRAN DAS,Kiran
5,ORD006,Rahul Sharma,Hyderabad,Clothing,Jeans,1,2200,UPI,5,2200,RAHUL SHARMA,Rahul
7,ORD008,Vikram Patel,Bangalore,Home,Chair,2,7500,UPI,3,15000,VIKRAM PATEL,Vikram
11,ORD012,Sneha Rao,Chennai,Clothing,Jacket,1,3500,Card,4,3500,SNEHA RAO,Sneha
12,ORD013,Kiran Das,Pune,Home,Lamp,2,1800,Cash,3,3600,KIRAN DAS,Kiran
14,ORD015,Vikram Patel,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,VIKRAM PATEL,Vikram

In [16]:
orders['Name_len'] = orders['Customer'].str.len()

Task 3 — Dynamic Sales Classification
Dataset: E-Commerce Orders

Concepts: Conditional transformation, np.where(), np.select()
1)  Create Sales_Level: Sales < 5000 = Low; 5000–20000 = Medium; 20000–50000 = High; Sales > 50000 = Very High.
2)  Create Customer_Type: Rating >= 4 = Satisfied; Rating < 4 = Needs Attention.
3)  Display Order_ID, Sales, Rating, Sales_Level, and Customer_Type.

In [17]:
def Sales_Level(sales):
  if sales < 5000:
    return 'Low'
  elif sales < 20000:
    return 'Medium'
  elif sales < 50000:
    return 'High'
  else:
    return 'Very High'

In [18]:
orders['Sales_level'] = orders['sales'].apply(Sales_Level)

In [19]:
orders.head(1)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,sales,Customer_upper,First_name,Name_len,Sales_level
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,RAHUL SHARMA,Rahul,12,Very High

In [20]:
def customer_rating (Rating):
  if Rating >= 4:
    return "Satisfied"
  else:
    return 'Needs Attention'

In [21]:
orders['Customer_Ratings'] = orders['Rating'].apply(customer_rating)

In [22]:
orders[['sales', 'Rating','Sales_level', 'Customer_Ratings']]

    sales  Rating Sales_level Customer_Ratings
0   65000       5   Very High        Satisfied
1    2400       4         Low        Satisfied
2   25000       5        High        Satisfied
3    5000       3      Medium  Needs Attention
4    6000       4      Medium        Satisfied
5    2200       5         Low        Satisfied
6   18000       4      Medium        Satisfied
7   15000       3      Medium  Needs Attention
8    2500       4         Low        Satisfied
9    4500       5         Low        Satisfied
10  30000       5        High        Satisfied
11   3500       4         Low        Satisfied
12   3600       3         Low  Needs Attention
13  12000       5      Medium        Satisfied
14   2400       4         Low        Satisfied

Task 4 — Product Search System
Dataset: E-Commerce Orders

Concepts: String filtering and logical conditions
1)  Find products containing 'phone', ignoring case.
2)  Find products containing 'lap' or 'tab'.
3)  Find products whose names contain more than 6 characters.
4)  Find products whose Category is not Clothing.
5)  Combine the conditions to find matching non-Clothing products.

In [23]:
orders[orders['Product'].str.contains('phone',case = False)]

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,sales,Customer_upper,First_name,Name_len,Sales_level,Customer_Ratings
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4,6000,KIRAN DAS,Kiran,9,Medium,Satisfied

In [24]:
orders[orders['Product'].str.contains(('lap|tab'),case = False)]

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,sales,Customer_upper,First_name,Name_len,Sales_level,Customer_Ratings
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,RAHUL SHARMA,Rahul,12,Very High,Satisfied
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5,30000,ARJUN KUMAR,Arjun,11,High,Satisfied

In [25]:
orders[orders['Product'].str.len() > 6]

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,sales,Customer_upper,First_name,Name_len,Sales_level,Customer_Ratings
1,ORD002,Priya Reddy,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,PRIYA REDDY,Priya,11,Low,Satisfied
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4,6000,KIRAN DAS,Kiran,9,Medium,Satisfied
6,ORD007,Anjali Singh,Mumbai,Electronics,Monitor,1,18000,Card,4,18000,ANJALI SINGH,Anjali,12,Medium,Satisfied
9,ORD010,Rohit Verma,Delhi,Electronics,Keyboard,3,1500,Cash,5,4500,ROHIT VERMA,Rohit,11,Low,Satisfied
13,ORD014,Anjali Singh,Mumbai,Electronics,Smartwatch,1,12000,UPI,5,12000,ANJALI SINGH,Anjali,12,Medium,Satisfied
14,ORD015,Vikram Patel,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,VIKRAM PATEL,Vikram,12,Low,Satisfied

In [26]:
orders[orders['Category'] != 'Clothing']

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,sales,Customer_upper,First_name,Name_len,Sales_level,Customer_Ratings
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,RAHUL SHARMA,Rahul,12,Very High,Satisfied
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5,25000,ARJUN KUMAR,Arjun,11,High,Satisfied
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3,5000,SNEHA RAO,Sneha,9,Medium,Needs Attention
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4,6000,KIRAN DAS,Kiran,9,Medium,Satisfied
6,ORD007,Anjali Singh,Mumbai,Electronics,Monitor,1,18000,Card,4,18000,ANJALI SINGH,Anjali,12,Medium,Satisfied
7,ORD008,Vikram Patel,Bangalore,Home,Chair,2,7500,UPI,3,15000,VIKRAM PATEL,Vikram,12,Medium,Needs Attention
9,ORD010,Rohit Verma,Delhi,Electronics,Keyboard,3,1500,Cash,5,4500,ROHIT VERMA,Rohit,11,Low,Satisfied
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5,30000,ARJUN KUMAR,Arjun,11,High,Satisfied
12,ORD013,Kiran Das,Pune,Home,Lamp,2,1800,Cash,3,3600,KIRAN DAS,Kiran,9,Low,Needs Attention
13,ORD014,Anjali Singh,Mumbai,Electronics,Smartwatch,1,12000,UPI,5,12000,ANJALI SINGH,Anjali,12,Medium,Satisfied

In [27]:
orders[(orders['Product'].str.contains('phone',case = False)) & (orders['Product'].str.contains(('lap|tab'),case = False)) & (orders['Product'].str.len() > 6) & (orders['Category'] != 'Clothing')]

Empty DataFrame
Columns: [Order_ID, Customer, City, Category, Product, Quantity, Unit_Price, Payment_Mode, Rating, sales, Customer_upper, First_name, Name_len, Sales_level, Customer_Ratings]
Index: []

Task 5 — Price & Quantity Investigation
Dataset: E-Commerce Orders

Concepts: Calculated columns, conditional classification, filtering, sorting

1)  Create Price_Category: Unit_Price < 2000 = Budget; 2000–10000 = Mid Range; 10000–30000 = Premium; >30000 = Luxury.
2)  Find Luxury products with Quantity > 1.
3)  Sort the result by Unit_Price descending.
4)  Display Product, Category, Quantity, Unit_Price, and Price_Category.

In [28]:
def get_price_category(Unit_Price):
  if Unit_Price < 2000:
    return 'Budget'
  elif Unit_Price < 10000:
    return 'Mid Range'
  elif Unit_Price < 30000:
    return 'Premium'
  else:
    return 'Luxury'

In [29]:
orders['Price_category'] = orders['Unit_Price'].apply(get_price_category)

In [32]:
orders[(orders['Price_category'] == 'Luxury') & (orders['Quantity']>1)]

Empty DataFrame
Columns: [Order_ID, Customer, City, Category, Product, Quantity, Unit_Price, Payment_Mode, Rating, sales, Customer_upper, First_name, Name_len, Sales_level, Customer_Ratings, Price_category]
Index: []

Task 6 — Employee Eligibility Analysis

Dataset: Employee Data

Concepts: loc, Boolean filtering, multiple conditions, sorting
1)  Find employees where Department = IT, Experience >= 5, Performance >= 4.3, and Salary >= 70000.
2)  Display Employee_ID, Name, Experience, Salary, and Performance.
3)  Sort the eligible employees by Performance descending.

In [33]:
employee = pd.read_csv('/content/Employee_Data_.csv')

In [34]:
employee.head()

   Employee_ID   Name Department  Experience  Salary  Performance
0          101  Rahul         IT           3   60000          4.5
1          102  Priya         HR           5   75000          4.2
2          103  Arjun         IT           2   50000          4.8
3          104  Sneha    Finance           7   90000          3.9
4          105  Kiran      Sales           4   65000          4.1

In [35]:
employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  12 non-null     int64
 1   Name         12 non-null     object
 2   Department   12 non-null     object
 3   Experience   12 non-null     int64
 4   Salary       12 non-null     int64
 5   Performance  12 non-null     float64
dtypes: float64(1), int64(3), object(2)
memory usage: 708.0+ bytes

In [45]:
employee[(employee['Department'] == 'IT') & (employee['Experience'] >= 5) & (employee['Performance'] >= 4.3) & (employee['Salary'] > 70000)].loc[:,['Employee_ID','Name','Experience','Salary','Performance']]

    Employee_ID    Name  Experience  Salary  Performance
5           106  Anjali           6   85000          4.7
11          112    Amit           6   80000          4.9

Task 7 — Salary Band & Promotion Flag

Dataset: Employee Data
Concepts: Conditional classification and derived columns

1)  Create Salary_Band: Salary < 60000 = Entry; 60000–75000 = Mid; 75000–90000 = Senior; >90000 = Lead.
2)  Create Promotion_Flag: Experience >= 5 AND Performance >= 4.5 = Review; otherwise No Review.
3)  Find employees with Promotion_Flag = Review.
4)  Display Name, Department, Experience, Salary, Performance, Salary_Band, and Promotion_Flag.

In [47]:
def get_salary_band(Salary):
  if Salary < 60000:
    return "Entry"
  elif Salary <75000:
    return 'Mid'
  elif Salary < 90000:
    return 'Senior'
  else:
    return 'Lead'

In [48]:
employee['Salary_Band'] = employee['Salary'].apply(get_salary_band)

In [49]:
def get_promotion_flag(Experience):
  if Experience >= 5 and Experience >= 4.5:
    return "Review"
  else:
    return "No Review"

In [50]:
employee['Promotion_Flag'] = employee['Experience'].apply(get_promotion_flag)

In [52]:
employee[employee['Promotion_Flag'] == 'Review']

,Employee_ID,Name,Department,Experience,Salary,Performance,Salary_Band,Promotion_Flag
1,102,Priya,HR,5,75000,4.2,Senior,Review
3,104,Sneha,Finance,7,90000,3.9,Lead,Review
5,106,Anjali,IT,6,85000,4.7,Senior,Review
8,109,Meena,Finance,8,95000,4.6,Lead,Review
9,110,Suresh,IT,5,70000,4.3,Mid,Review
11,112,Amit,IT,6,80000,4.9,Senior,Review

In [53]:
employee.loc[:,['Name','Department', 'Experience', 'Salary', 'Performance', 'Salary_Band','Promotion_Flag']]

,Name,Department,Experience,Salary,Performance,Salary_Band,Promotion_Flag
0,Rahul,IT,3,60000,4.5,Mid,No Review
1,Priya,HR,5,75000,4.2,Senior,Review
2,Arjun,IT,2,50000,4.8,Entry,No Review
3,Sneha,Finance,7,90000,3.9,Lead,Review
4,Kiran,Sales,4,65000,4.1,Mid,No Review
5,Anjali,IT,6,85000,4.7,Senior,Review
6,Vikram,Sales,3,55000,3.8,Entry,No Review
7,Rohit,HR,2,48000,3.5,Entry,No Review
8,Meena,Finance,8,95000,4.6,Lead,Review
9,Suresh,IT,5,70000,4.3,Mid,Review
10,Pooja,Sales,4,62000,4.0,Mid,No Review
11,Amit,IT,6,80000,4.9,Senior,Review

Task 8 — Employee Data Cleaning

Dataset: Employee Data
Concepts: isna(), fillna(), median(), duplicated(), drop_duplicates()

1)  Create a dirty copy of the employee dataset.
2)  Set Salary at row index 2 to missing and Department at row index 5 to missing.
3)  Append a duplicate of row index 1.
4)  Find missing values and duplicate records.
5)  Remove duplicates.
6)  Fill missing Salary using the median Salary.
7)  Fill missing Department with 'Unknown'.
Verify that no missing values or duplicates remain

In [54]:
employee_dirty = employee.copy()

In [62]:
employee_dirty.loc[2, 'Salary'] = np.nan
employee_dirty.loc[5, 'Department'] = np.nan
employee_dirty = pd.concat([employee, employee.loc[[1]]], ignore_index=True)

In [70]:
employee_dirty.isnull().sum()

Employee_ID       0
Name              0
Department        0
Experience        0
Salary            0
Performance       0
Salary_Band       0
Promotion_Flag    0
dtype: int64

In [71]:
employee_dirty.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
dtype: bool

In [73]:
employee_dirty = employee_dirty.drop_duplicates()

In [69]:
employee_dirty['Salary'] = employee_dirty['Salary'].fillna(employee_dirty['Salary'].median())

In [59]:
employee_dirty = employee_dirty.drop_duplicates()

In [77]:
employee_dirty['Department'] = employee_dirty['Department'].fillna('Unknown')

0          IT
1          HR
2          IT
3     Finance
4       Sales
5          IT
6       Sales
7          HR
8     Finance
9          IT
10      Sales
11         IT
Name: Department, dtype: object

In [78]:
employee_dirty.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee_ID     12 non-null     int64
 1   Name            12 non-null     object
 2   Department      12 non-null     object
 3   Experience      12 non-null     int64
 4   Salary          12 non-null     float64
 5   Performance     12 non-null     float64
 6   Salary_Band     12 non-null     object
 7   Promotion_Flag  12 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 864.0+ bytes

Task 9 — Student Risk Analysis
Dataset: Student Performance

Concepts: Arithmetic, calculated columns, conditional classification
1) Create Final_Score = Assignment_Score × 0.40 + Exam_Score × 0.60.
2) Create Status: >=85 = Excellent; 70–84 = Good; 50–69 = Needs Improvement; <50 = At Risk.
3) Find students where Attendance < 80 AND Final_Score < 70.
4) Display Student_ID, Name, Course, Attendance, Final_Score, and Status.

In [79]:
student = pd.read_csv('/content/Student_Performance.csv')

In [80]:
student.head()

  Student_ID   Name      Course  Attendance  Assignment_Score  Exam_Score
0       S001  Rahul      Python          92                85          88
1       S002  Priya      Python          85                78          80
2       S003  Arjun  JavaScript          78                65          70
3       S004  Sneha      Python          95                92          94
4       S005  Kiran         SQL          88                88          91

In [81]:
student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        10 non-null     object
 1   Name              10 non-null     object
 2   Course            10 non-null     object
 3   Attendance        10 non-null     int64
 4   Assignment_Score  10 non-null     int64
 5   Exam_Score        10 non-null     int64
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [82]:
student['Final_Score'] = student['Assignment_Score']*0.40 + student['Exam_Score'] * 0.60

In [83]:
def status(Final_Score):
  if Final_Score >= 85:
    return 'Excellent'
  elif Final_Score >= 84:
    return 'Good'
  elif Final_Score >= 69:
    return 'Needs Improvement'
  else:
    return 'At Risk'

In [84]:
student['Status'] = student['Final_Score'].apply(status)

In [86]:
student[(student['Attendance'] < 80) & (student['Final_Score'] < 70)]

,Student_ID,Name,Course,Attendance,Assignment_Score,Exam_Score,Final_Score,Status
2,S003,Arjun,JavaScript,78,65,70,68.0,At Risk
6,S007,Vikram,SQL,72,60,58,58.8,At Risk

In [87]:
student.loc[:,['Student_ID', 'Name', 'Course', 'Attendance', 'Final_Score','Status']]

  Student_ID    Name      Course  Attendance  Final_Score             Status
0       S001   Rahul      Python          92         86.8          Excellent
1       S002   Priya      Python          85         79.2  Needs Improvement
2       S003   Arjun  JavaScript          78         68.0            At Risk
3       S004   Sneha      Python          95         93.2          Excellent
4       S005   Kiran         SQL          88         89.8          Excellent
5       S006  Anjali      Python          91         91.8          Excellent
6       S007  Vikram         SQL          72         58.8            At Risk
7       S008   Rohit  JavaScript          89         76.8  Needs Improvement
8       S009   Meena      Python          96         95.6          Excellent
9       S010   Pooja         SQL          80         83.8  Needs Improvement

Task 10 — Complete Analyst Challenge
Dataset: E-Commerce Orders
Concepts: Combined Day 1–8 workflow; no groupby() or aggregation

1) Create Revenue = Quantity × Unit_Price.
2) Create Discount_Rate: Revenue >= 50000 = 15%; Revenue >= 20000 = 10%; otherwise 5%.
3) Calculate Discount_Amount and Final_Revenue.
4) Create Customer_Status: Rating >= 4 = Satisfied; otherwise Needs Attention.
5) Find orders where Category = Electronics AND Final_Revenue > 20000 AND Rating >= 4 AND Payment_Mode = UPI.
6) Sort qualifying orders by Final_Revenue descending.
7) Return Order_ID, Customer, City, Product, Quantity, Revenue, Discount_Amount, Final_Revenue, and Rating.
8) Create Order_Label such as: ORD001 - Laptop - ₹55250.

In [88]:
orders['Revenue'] = orders['Quantity'] * orders['Unit_Price']

In [90]:
conditions = [
    orders['Revenue'] >= 50000,
    orders['Revenue'] >= 20000
]
rates = [0.15, 0.10]

orders['Discount_Rate'] = np.select(conditions, rates, default=0.05)

orders['Discount_Amount'] = orders['Revenue'] * orders['Discount_Rate']
orders['Final_Revenue'] = orders['Revenue'] - orders['Discount_Amount']

In [91]:
def get_customer_ratings(Rating):
  if Rating >= 4:
    return 'Satisfied'
  else:
    return'Attention'

In [92]:
orders['Customer_Rating'] = orders['Rating'].apply(get_customer_ratings)

In [94]:
orders[(orders['Category'] == 'Electonics') & (orders['Final_Revenue']>20000) & (orders['Rating'] >= 4) & (orders['Payment_Mode'] == 'UPI')]

Empty DataFrame
Columns: [Order_ID, Customer, City, Category, Product, Quantity, Unit_Price, Payment_Mode, Rating, sales, Customer_upper, First_name, Name_len, Sales_level, Customer_Ratings, Price_category, Revenue, Discount_Rate, Discount_Amount, Final_Revenue, Customer_Rating]
Index: []

[0 rows x 21 columns]

In [95]:
orders.loc[:,['Order_ID', 'Customer', 'City', 'Product', 'Quantity', 'Revenue', 'Discount_Amount', 'Final_Revenue','Rating']]

,Order_ID,Customer,City,Product,Quantity,Revenue,Discount_Amount,Final_Revenue,Rating
0,ORD001,Rahul Sharma,Hyderabad,Laptop,1,65000,9750.0,55250.0,5
1,ORD002,Priya Reddy,Bangalore,T-Shirt,2,2400,120.0,2280.0,4
2,ORD003,Arjun Kumar,Hyderabad,Mobile,1,25000,2500.0,22500.0,5
3,ORD004,Sneha Rao,Chennai,Mixer,1,5000,250.0,4750.0,3
4,ORD005,Kiran Das,Pune,Headphones,2,6000,300.0,5700.0,4
5,ORD006,Rahul Sharma,Hyderabad,Jeans,1,2200,110.0,2090.0,5
6,ORD007,Anjali Singh,Mumbai,Monitor,1,18000,900.0,17100.0,4
7,ORD008,Vikram Patel,Bangalore,Chair,2,15000,750.0,14250.0,3
8,ORD009,Priya Reddy,Bangalore,Shoes,1,2500,125.0,2375.0,4
9,ORD010,Rohit Verma,Delhi,Keyboard,3,4500,225.0,4275.0,5
10,ORD011,Arjun Kumar,Hyderabad,Tablet,1,30000,3000.0,27000.0,5
11,ORD012,Sneha Rao,Chennai,Jacket,1,3500,175.0,3325.0,4
12,ORD013,Kiran Das,Pune,Lamp,2,3600,180.0,3420.0,3
13,ORD014,Anjali Singh,Mumbai,Smartwatch,1,12000,600.0,11400.0,5
14,ORD015,Vikram Patel,Bangalore,T-Shirt,2,2400,120.0,2280.0,4

In [96]:
employee['Order_Label'] = employee.apply(lambda row: f"{row['Order_ID']} - {row['Product']} - ₹{int(row['Final_Revenue'])}", axis=1)

KeyError: 'Order_ID'